cache:
  key: "$CI_JOB_REF_NAME"
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "-s resources/maven/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - test-sources
  - integration
  - deploy

test-sources-jdk7:
  stage: test-sources
  image: maven:3.3.9-jdk-7
  script:
    - mvn $MAVEN_CLI_OPTS clean test -T 2C;

test-sources-jdk8:
  stage: test-sources
  image: maven:3.3.9-jdk-8
  script:
    - mvn $MAVEN_CLI_OPTS clean test -T 2C;

integration-jdk-7:
  stage: integration
  image: maven:3.3.9-jdk-7
  script:
    - mvn $MAVEN_CLI_OPTS clean install -T 2C;
    - cd integration/activiti/activiti-integration-5_12-6_x
    - echo "Running test profile for Activiti version 5.12";
    - mvn $MAVEN_CLI_OPTS clean dependency:tree test -P activiti-5.12;
    - echo "Running test profile for Activiti version 6.0.0";
    - mvn $MAVEN_CLI_OPTS clean dependency:tree test -P activiti-6.0.0;

integration-jdk-8:
  stage: integration
  script: "resources/scripts/ci/ci.sh"
  image: maven:3.3.9-jdk-8

deploy:
  stage: deploy
  script: mvn $MAVEN_CLI_OPTS clean deploy
  image: maven:3.3.9-jdk-8